language: python
dist: trusty
sudo: required
env:
  global:
    - secure: Fd+dALSXhRgP44UaiED0xbJMHLxzON1Vcu6ufxDGgyl9NYepT0cfMGczLocfawc35ig++SyfytfpaPRhy3yG7WhNiBmpq+M1rec5MDKh/tFSKV/JOmLxbUIAxByIgTH39e+bY2El0h+vqiB12JiArahBzraYMYY+Xkty3Ysr+9o=
    - secure: clvOWlojaHQMHGhrN+sG+jOVLAsGJQFpzlUBv+8tKNy+Xbv/XPOQvnzqFTCdRlHSd39wnwIQTwOCWaCYhEECEyqgpaxYlYpSPsUOmk12aSxfjH5YGdwFqZvqhw1rkBpaEyoLh4PT0d1oLeCcJvb0jNuU4YbYOtq7DIRJDih/hPg=
matrix:
  fast_finish: true
  include:
    - env: GLTEST='build_and_install'
      python: "2.7"

    - env: GLTEST='unit' GLREQUIREMENTS='precise'
      python: "2.7"

    - env: GLTEST='unit' GLREQUIREMENTS='trusty'
      python: "2.7"

    - env: GLTEST='unit' GLREQUIREMENTS='xenial'
      python: "2.7"

    - env: GLTEST='unit' GLREQUIREMENTS='wheezy'
      python: "2.7"

    - env: GLTEST='unit' GLREQUIREMENTS='jessie'
      python: "2.7"

    - env: GLTEST='unit' GLREQUIREMENTS='stretch'
      python: "2.7"

    - env: GLTEST='end2end-0' BROWSER='ie 9'
      python: "2.7"
      addons:
        sauce_connect: true

    - env: GLTEST='end2end-1' BROWSER='ie 10'
      python: "2.7"
      addons:
        sauce_connect: true

    - env: GLTEST='end2end-2' BROWSER='ie 11'
      python: "2.7"
      addons:
        sauce_connect: true

    - env: GLTEST='end2end-3' BROWSER='edge 20.10240'
      python: "2.7"
      addons:
        sauce_connect: true

    - env: GLTEST='end2end-4' BROWSER='firefox 34'
      python: "2.7"
      addons:
        sauce_connect: true

    - env: GLTEST='end2end-5' BROWSER='firefox 43'
      python: "2.7"
      addons:
        sauce_connect: true

    - env: GLTEST='end2end-6' BROWSER='firefox beta'
      python: "2.7"
      addons:
        sauce_connect: true

    - env: GLTEST='end2end-7' BROWSER='chrome 37'
      python: "2.7"
      addons:
        sauce_connect: true

    - env: GLTEST='end2end-8' BROWSER='chrome 47'
      python: "2.7"
      addons:
        sauce_connect: true

    - env: GLTEST='end2end-9' BROWSER='chrome beta'
      python: "2.7"
      addons:
        sauce_connect: true

    - env: GLTEST='end2end-10' BROWSER='safari 8'
      python: "2.7"
      addons:
        sauce_connect: true

    - env: GLTEST='end2end-11' BROWSER='safari 9'
      python: "2.7"
      addons:
        sauce_connect: true

    - env: GLTEST='end2end-12' BROWSER='android 4.4'
      python: "2.7"
      addons:
        sauce_connect: true

    - env: GLTEST='end2end-13' BROWSER='android 5.1'
      python: "2.7"
      addons:
        sauce_connect: true

    - env: GLTEST='end2end-14' BROWSER='iphone 7.1'
      python: "2.7"
      addons:
        sauce_connect: true

    - env: GLTEST='end2end-15' BROWSER='iphone 9.2'
      python: "2.7"
      addons:
        sauce_connect: true

  allow_failures:
    - env: GLTEST='end2end-0' BROWSER='ie 9'
    - env: GLTEST='end2end-1' BROWSER='ie 10'
    - env: GLTEST='end2end-2' BROWSER='ie 11'
    - env: GLTEST='end2end-3' BROWSER='edge 20.10240'
    - env: GLTEST='end2end-4' BROWSER='firefox 34'
    - env: GLTEST='end2end-5' BROWSER='firefox 43'
    - env: GLTEST='end2end-6' BROWSER='firefox beta'
    - env: GLTEST='end2end-7' BROWSER='chrome 37'
    - env: GLTEST='end2end-8' BROWSER='chrome 47'
    - env: GLTEST='end2end-9' BROWSER='chrome beta'
    - env: GLTEST='end2end-10' BROWSER='safari 8'
    - env: GLTEST='end2end-11' BROWSER='safari 9'
    - env: GLTEST='end2end-12' BROWSER='android 4.4'
    - env: GLTEST='end2end-13' BROWSER='android 5.1'
    - env: GLTEST='end2end-14' BROWSER='iphone 7.1'
    - env: GLTEST='end2end-15' BROWSER='iphone 9.2'
before_install:
  - nvm install 4.2
  - nvm use 4.2
install: true
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3 # give xvfb some time to start
script:
  - $TRAVIS_BUILD_DIR/scripts/travis.sh
